exports.showHomePage=function(req,res){
    res.render("./index",{
        page:"index"
    });
}
exports.showLoginPage=function(req,res){
    res.render("./login",{
        page:"login"
    });
}
exports.showChangePreferencesPage=function(req,res){
    res.render("./ChangePreferences",{
        page:"ChangePreferences"
    });
}
exports.showParameterPage=function(req,res){
    res.render("./Parameter",{
        page:"Parameter"
    });
}
exports.getRegisterPage=function(req,res){
    res.render("./register",{
        page:"register"
    });
}
exports.getGeneralPage=function(req,res){
    res.render("./General",{
        pageCategory:"General", 
    });
}
exports.getHealthPage=function(req,res){
    res.render("./Health",{
        pageCategory:"Health"
    });
}
exports.getEntertainmentPage=function(req,res){
    res.render("./Entertainment",{
        pageCategory:"Entertainment"
    });
}
exports.getSciencePage=function(req,res){
    res.render("./Science",{
        pageCategory:"Science"
    });
}
exports.getSportPage=function(req,res){
    res.render("./Sport",{
        pageCategory:"Sport",
        nameCategoryAPI: "sport" //ici on a pas le meme nom pour l uri de fetch de lapi que le nom de la page
    });
}
exports.getTechnologyPage=function(req,res){
    res.render("./Technology",{
        pageCategory:"Technology"
    });
}
exports.getEmailPage=function(req,res){
    res.render("./Email",{
        page:"Email"
    });
}