exports.showHomePage=function(req,res){
    res.render("./index",{
        page:"index"
    });
}
exports.showLoginPage=function(req,res){
    res.render("./login",{
        page:"login"
    });
}
exports.showModifierPreferencesPage=function(req,res){
    res.render("./ModifierPreferences",{
        page:"ModifierPreferences"
    });
}
exports.showParametrePage=function(req,res){
    res.render("./Parametre",{
        page:"Parametre"
    });
}
exports.getRegisterPage=function(req,res){
    res.render("./register",{
        page:"register"
    });
}
exports.getGeneralPage=function(req,res){
    res.render("./General",{
        page:"General"
    });
}
exports.getHealthPage=function(req,res){
    res.render("./Health",{
        page:"Health"
    });
}
exports.getEntertainmentPage=function(req,res){
    res.render("./Entertainment",{
        page:"Entertainment"
    });
}
exports.getSciencePage=function(req,res){
    res.render("./Science",{
        page:"Science"
    });
}
exports.getSportPage=function(req,res){
    res.render("./Sport",{
        page:"Sport"
    });
}
exports.getTechnologyPage=function(req,res){
    res.render("./Technology",{
        page:"Technology"
    });
}
exports.getEmailPage=function(req,res){
    res.render("./Email",{
        page:"Email"
    });
}